import test from 'node:test';import assert from 'node:assert/strict';
import {empty,addProduct,create,operation,transition,snapshot,claim,deliver,ack,fail,replay,cleanup,experiment,DomainError} from '../lib/domain.mjs';
function setup(){const s=empty();addProduct(s,'A','Example A',12345,10);addProduct(s,'B','Example B',5000,3);return s;}
const body=(key='key',items=[{sku:'A',quantity:1}])=>({customer:'Demo',request_key:key,items,ttl:300});
test('multi-item order uses integer money and balanced stock',()=>{const s=setup(),o=create(s,body('x',[{sku:'A',quantity:2},{sku:'B',quantity:3}]),0);assert.equal(o.total,39690);assert.ok(snapshot(s,0).metrics.inventory_balanced);});
test('second product failure preserves every item and produces no event',()=>{const s=setup(),before=structuredClone(s);assert.throws(()=>operation(s,'orders',body('x',[{sku:'A',quantity:2},{sku:'B',quantity:4}]),0));assert.deepEqual(s,before);});
test('canonical request retry has one effect; changed payload conflicts',()=>{const s=setup(),items=[{sku:'B',quantity:1},{sku:'A',quantity:1}],first=create(s,body('x',items),0);assert.equal(create(s,body('x',[...items].reverse()),0).id,first.id);assert.equal(s.events.length,1);assert.throws(()=>create(s,{...body('x',items),ttl:60},0),DomainError);});
test('repeated cancel restores stock once',()=>{const s=setup(),o=create(s,body(),0);transition(s,o.id,'cancel',0);transition(s,o.id,'cancel',0);assert.equal(s.products[0].available,10);assert.equal(s.events.length,2);});
test('confirmed order is final and consumes stock',()=>{const s=setup(),o=create(s,body(),0);transition(s,o.id,'confirm',0);assert.throws(()=>transition(s,o.id,'cancel',0));assert.equal(snapshot(s,0).products[0].sold,1);});
test('expiry at exact boundary restores stock once',()=>{const s=setup();create(s,{...body(),ttl:5},0);assert.equal(cleanup(s,5),1);assert.equal(cleanup(s,6),0);assert.equal(s.products[0].available,10);});
test('expiry operation reports actual cleaned count',()=>{const s=setup();create(s,{...body(),ttl:5},0);assert.equal(operation(s,'cleanup',{},5).result.expired,1);});
test('delivery-before-ack retry deduplicates and fences stale claim',()=>{const s=setup();create(s,body(),0);const first=claim(s,3);assert.ok(deliver(s,first,3));const second=claim(s,19);assert.equal(ack(s,first,19),false);assert.equal(deliver(s,first,19),false);assert.ok(deliver(s,second,19));assert.ok(ack(s,second,19));assert.equal(s.inbox.length,1);});
test('three failures dead-letter; replay keeps event identity',()=>{const s=setup();create(s,body(),0);let now=3,e;for(let n=1;n<=3;n++){e=claim(s,now);assert.equal(e.attempts,n);fail(s,e,now);now+=2**n;}assert.equal(s.events[0].state,'dead');replay(s,e.id,now);assert.equal(s.events[0].id,e.id);assert.equal(s.events[0].attempts,0);});
test('automatic delivery and paused mode differ',()=>{const s=setup();create(s,body(),0);assert.equal(operation(s,'snapshot',{},4).result.metrics.received_events,1);s.auto=false;assert.equal(operation(s,'snapshot',{},4).result.metrics.received_events,0);});
test('invalid integer quantities and duplicate products rejected',()=>{for(const items of [[{sku:'A',quantity:true}],[{sku:'A',quantity:1.5}],[{sku:'A',quantity:1},{sku:'A',quantity:2}]])assert.throws(()=>create(setup(),body('x',items),0));});
test('workspace clones do not affect another workspace',()=>{const a=setup(),b=setup();operation(a,'orders',body(),0);assert.equal(b.orders.length,0);assert.equal(b.products[0].available,10);});
test('demo evidence reports only achieved scope',()=>{const c=experiment('contention'),r=experiment('crash');assert.equal(c.accepted,10);assert.equal(c.rejected,40);assert.ok(c.balanced);assert.match(c.scope,/sequential/);assert.equal(r.inbox_rows_after,1);assert.ok(r.stale_ack_rejected);});
