export class DomainError extends Error { constructor(message,status=409){super(message);this.status=status;} }
const id=()=>crypto.randomUUID();
export function empty(){return {products:[],orders:[],events:[],audit:[],inbox:[],auto:true,actions:[],version:1};}
const clone=s=>structuredClone(s);
function text(value,label,max){if(typeof value!=='string'||!value.trim()||value.length>max)throw new DomainError(label+' is invalid.',422);return value.trim();}
function integer(value,label,min,max){if(!Number.isSafeInteger(value)||value<min||value>max)throw new DomainError(label+' is invalid.',422);return value;}
function record(s,oid,kind,now,detail={}){s.audit.push({id:s.audit.length+1,order_id:oid,action:kind,at:now,detail:JSON.stringify(detail)});if(oid)s.events.push({id:id(),order_id:oid,kind,payload:{...detail},state:'pending',attempts:0,due:now+3,token:null,lease:null,error:null});if(s.audit.length>500)s.audit=s.audit.slice(-500);}
export function addProduct(s,sku,name,price,quantity){s.products.push({sku,name,price,available:quantity,received:quantity});}
export function cleanup(s,now){let count=0;for(const order of s.orders){if(order.state==='held'&&order.expires<=now){for(const line of order.items)s.products.find(p=>p.sku===line.sku).available+=line.quantity;order.state='expired';record(s,order.id,'order.expired',now);count++;}}return count;}
export function create(s,body,now){
 const customer=text(body.customer,'Customer alias',60),key=text(body.request_key,'Request key',128),ttl=integer(body.ttl??300,'Reservation lifetime',5,3600);
 if(!Array.isArray(body.items)||body.items.length<1||body.items.length>20)throw new DomainError('Choose 1 to 20 products.',422);
 const seen=new Set(),items=body.items.map(item=>{if(!item||Object.keys(item).sort().join(',')!=='quantity,sku')throw new DomainError('Each item needs SKU and quantity.',422);const sku=text(item.sku,'SKU',64),quantity=integer(item.quantity,'Quantity',1,1000);if(seen.has(sku))throw new DomainError('Combine duplicate products into one line.',422);seen.add(sku);return {sku,quantity};}).sort((a,b)=>a.sku.localeCompare(b.sku));
 const fingerprint=JSON.stringify({customer,items,ttl}),old=s.orders.find(o=>o.request_key===key);
 if(old){if(old.fingerprint!==fingerprint)throw new DomainError('That request key belongs to a different order.');return clone(old);}
 if(s.orders.length>=100)throw new DomainError('This demo workspace has reached 100 orders. Start a fresh demo.',429);
 // Check every line before applying changes; the enclosing compare-and-swap commits the whole state.
 for(const line of items){const p=s.products.find(p=>p.sku===line.sku);if(!p||p.available<line.quantity)throw new DomainError('Insufficient stock for '+line.sku+'. No products were reserved.');}
 let total=0;const priced=items.map(line=>{const p=s.products.find(p=>p.sku===line.sku);p.available-=line.quantity;total+=p.price*line.quantity;return {...line,name:p.name,unit_price:p.price};});
 const order={id:id(),request_key:key,fingerprint,customer,state:'held',total,created:now,expires:now+ttl,items:priced};s.orders.push(order);record(s,order.id,'order.held',now,{total_paise:total});return clone(order);
}
export function transition(s,oid,action,now){if(!['confirm','cancel'].includes(action))throw new DomainError('Choose confirm or cancel.',422);const row=s.orders.find(o=>o.id===oid);if(!row)throw new DomainError('Order not found.',404);const state=action==='confirm'?'confirmed':'cancelled';if(row.state===state)return clone(row);if(row.state!=='held')throw new DomainError('Order is already '+row.state+'.');if(state==='cancelled')for(const item of row.items)s.products.find(p=>p.sku===item.sku).available+=item.quantity;row.state=state;record(s,oid,'order.'+state,now);return clone(row);}
export function recover(s,now){for(const event of s.events)if(event.state==='processing'&&event.lease<=now){event.state=event.attempts>=3?'dead':'pending';event.due=now;event.token=null;event.lease=null;event.error='Worker lease expired';}}
export function claim(s,now){recover(s,now);const e=s.events.find(e=>e.state==='pending'&&e.due<=now);if(!e)return null;e.state='processing';e.attempts++;e.token=id();e.lease=now+15;return clone(e);}
function current(s,e,now){return s.events.find(x=>x.id===e.id&&x.token===e.token&&x.state==='processing'&&x.lease>now);}
export function deliver(s,event,now){if(!current(s,event,now))return false;if(!s.inbox.some(i=>i.event_id===event.id))s.inbox.push({event_id:event.id,kind:event.kind,received:now});return true;}
export function ack(s,event,now){const e=current(s,event,now);if(!e)return false;e.state='sent';e.token=null;e.lease=null;e.error=null;return true;}
export function fail(s,event,now){const e=current(s,event,now);if(!e)return false;e.state=e.attempts>=3?'dead':'pending';e.due=now+2**e.attempts;e.token=null;e.lease=null;e.error='Simulated delivery failure';return true;}
export function processOne(s,now,simulate=false){const event=claim(s,now);if(!event)return {processed:false};if(simulate){fail(s,event,now);return {processed:true,delivered:false};}const delivered=deliver(s,event,now),acknowledged=delivered&&ack(s,event,now);return {processed:true,delivered,acknowledged};}
export function replay(s,eid,now){const e=s.events.find(e=>e.id===eid);if(!e)throw new DomainError('Event not found.',404);if(e.state!=='dead')throw new DomainError('Only dead-letter events can be replayed.');e.state='pending';e.attempts=0;e.due=now;e.error=null;record(s,null,'event.replayed',now,{event_id:eid});return {replayed:true};}
export function restock(s,sku,quantity,now){integer(quantity,'Quantity',1,1000);const p=s.products.find(p=>p.sku===sku);if(!p)throw new DomainError('Product not found.',404);if(p.received+quantity>1000000)throw new DomainError('Demo stock limit reached.',429);p.available+=quantity;p.received+=quantity;record(s,null,'stock.received',now,{sku,quantity});return {restocked:true};}
export function snapshot(s,now){const products=s.products.map(p=>{let held=0,sold=0;for(const o of s.orders)for(const i of o.items)if(i.sku===p.sku){if(o.state==='held')held+=i.quantity;if(o.state==='confirmed')sold+=i.quantity;}return {...p,held,sold,balanced:p.received===p.available+held+sold};});const counts=rows=>rows.reduce((result,r)=>(result[r.state]=(result[r.state]||0)+1,result),{});return {products,orders:clone([...s.orders].reverse()).map(({fingerprint,...o})=>o),events:clone([...s.events].reverse()).map(({token,payload,...e})=>e),audit:clone([...s.audit].reverse()),inbox:clone([...s.inbox].reverse()),now,list_limit:100,auto:s.auto,metrics:{order_counts:counts(s.orders),event_counts:counts(s.events),confirmed_value_paise:s.orders.filter(o=>o.state==='confirmed').reduce((n,o)=>n+o.total,0),received_events:s.inbox.length,inventory_balanced:products.every(p=>p.balanced)}};}
export function seed(now){const s=empty();for(const p of [['BAG-01','Everyday backpack',149900,18],['BOTTLE-01','Steel water bottle',69900,30],['HEAD-01','Wireless headphones',249900,8],['NOTE-01','Dotted notebook',24900,50],['LAMP-01','Desk lamp',129900,12]])addProduct(s,...p);create(s,{customer:'Campus store',items:[{sku:'BAG-01',quantity:2},{sku:'NOTE-01',quantity:3}],request_key:'sample-campus',ttl:3600},now);const o=create(s,{customer:'Demo buyer',items:[{sku:'BOTTLE-01',quantity:1}],request_key:'sample-buyer',ttl:3600},now);transition(s,o.id,'confirm',now);for(const e of s.events)e.due=now;for(let i=0;i<3;i++)processOne(s,now);return s;}
export function experiment(kind){const s=empty();addProduct(s,'A','Example',10000,10);if(kind==='contention'){let accepted=0;for(let i=0;i<50;i++){try{create(s,{customer:'Buyer '+i,items:[{sku:'A',quantity:1}],request_key:'request-'+i},0);accepted++;}catch(e){if(!(e instanceof DomainError))throw e;}}return {accepted,rejected:50-accepted,remaining:s.products[0].available,balanced:snapshot(s,0).metrics.inventory_balanced,scope:'Hosted demo: 50 sequential domain submissions. Run the Python experiment for eight-thread contention evidence.'};}if(kind==='crash'){create(s,{customer:'Demo',items:[{sku:'A',quantity:1}],request_key:'crash'},0);s.events[0].due=0;const first=claim(s,0);deliver(s,first,0);const second=claim(s,16),stale=ack(s,first,16);deliver(s,second,16);ack(s,second,16);return {deliveries_attempted:2,inbox_rows_after:s.inbox.length,stale_ack_rejected:!stale,event_state:s.events[0].state,scope:'Deterministic hosted state-machine simulation; local receiver effects deduplicated by event ID.'};}throw new DomainError('Unknown experiment.',404);}
export function operation(input,path,body,now){const s=clone(input);if(path!=='snapshot'){s.actions=(s.actions||[]).filter(t=>now-t<60);if(s.actions.length>=60)throw new DomainError('Demo action limit reached. Wait one minute.',429);s.actions.push(now);}const expired=cleanup(s,now);recover(s,now);let result;
 if(path==='snapshot'){if(s.auto)for(let i=0;i<4;i++){if(!processOne(s,now).processed)break;}result=snapshot(s,now);}
 else if(path==='orders')result=create(s,body,now);
 else if(/^orders\/[^/]+\/(confirm|cancel)$/.test(path)){const [,oid,action]=path.split('/');result=transition(s,oid,action,now);}
 else if(/^products\/[^/]+\/restock$/.test(path)){const [,sku]=path.split('/');result=restock(s,decodeURIComponent(sku),body.quantity,now);}
 else if(path==='events/process')result=processOne(s,now,body.simulate_failure===true);
 else if(/^events\/[^/]+\/replay$/.test(path))result=replay(s,path.split('/')[1],now);
 else if(path==='cleanup')result={expired};
 else if(path==='automation'){if(typeof body.enabled!=='boolean')throw new DomainError('Choose on or off.',422);s.auto=body.enabled;result={enabled:s.auto};}
 else throw new DomainError('Route not found.',404);
 return {state:s,result};}
